WINDSURF_GLOBAL_RULE_SRC := $(HOME)/dev/dotprofile/windsurf/global_rules.md
WINDSURF_GLOBAL_RULE_DST := $(HOME)/.codeium/windsurf/memories/global_rules.md

.PHONY: set-windsurf-global-rule
set-windsurf-global-rule:
	ln -sf $(WINDSURF_GLOBAL_RULE_SRC) $(WINDSURF_GLOBAL_RULE_DST)
